# Generated by Django 3.2.5 on 2021-12-03 12:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_auto_20211130_2234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='The name of the club must contain at least three character of any kind!', regex='^\\w{3,}$')])),
                ('population', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('location', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=520)),
            ],
        ),
    ]
