# Generated by Django 3.2.5 on 2021-12-03 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_club'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='population',
        ),
    ]
