# Generated by Django 3.2.5 on 2021-12-03 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_auto_20211202_1234'),
        ('clubs', '0005_remove_club_population'),
    ]

    operations = [
    ]
