# Generated by Django 3.2.5 on 2021-12-10 18:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0009_match_tournament_tournamentofficer_tournamentparticipant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='The name of the club must contain at least three character of any kind!', regex='^.{3,}$')]),
        ),
    ]
